feat(plugin): validate file sizes (fixes 145)
yext/pages pull request #147
Opened 2022-08-03 19:40 UTC by mkilpatrick

2022-08-03 20:35 UTC, mancusi requested changes
can you add tests?

2022-08-03 20:35 UTC, mancusi commented on packages/pages/src/vite-plugin/build/closeBundle/moduleLoader.ts
> +const validateBundles = (serverBundlePaths: string[]) => {
The server bundle paths aren't the only assets included in the plugin. Everything in the static and renderer folder are also included (see the ci.json file in the starter or the artifact output )

2022-08-04 15:55 UTC, mancusi requested changes

2022-08-04 15:55 UTC, mancusi commented on packages/pages/src/vite-plugin/build/closeBundle/bundleValidator.ts
> +export const validateBundles = () => {
this isn't all the bundles -- just the server-side bundles. should that be noted?

2022-08-04 15:55 UTC, mancusi commented on packages/pages/src/vite-plugin/build/closeBundle/bundleValidator.test.ts
> +    jest.spyOn(glob, "sync").mockImplementation(() => ["file1.js", "file2.js"]);
make sure to restoreAllMocks
https://jestjs.io/docs/jest-object#jestspyonobject-methodname

2022-08-04 15:57 UTC, mancusi commented
General comment, the fact that we're doing this validation now ties the ci.json configuration in the repo to versions of @yext/pages. This doesn't particularly desirable. I think we should start auto-generating this plugin configuration

2022-08-04 21:04 UTC, jimboHenris commented
> General comment, the fact that we're doing this validation now ties the ci.json configuration in the repo to versions of @yext/pages. This doesn't particularly desirable. I think we should start auto-generating this plugin configuration

Sorry, I'm not sure I follow this. Which plugin configuration would we autogen? And where is the coupling?

2022-08-05 00:08 UTC, mkilpatrick commented
> General comment, the fact that we're doing this validation now ties the ci.json configuration in the repo to versions of @yext/pages. This doesn't particularly desirable. I think we should start auto-generating this plugin configuration

Agreed. We talked offline and this will be desirable to do in the future, but we already have this loose coupling now so this CR shouldn't impact or make anything worse.

> Sorry, I'm not sure I follow this. Which plugin configuration would we autogen? And where is the coupling?

We'd autogen the `artifactStructure` portion of ci.json (except it'll need to live in its own file. The coupling now is that PagesJS assumes the dist/assets folders (hard coded) and that setup is defined in the starter's ci.json. If we change something on either side things won't work.

2022-08-05 17:14 UTC, jimboHenris approved these changes

2022-08-05 20:43 UTC, mancusi approved these changes
LGTM if we're not going to do the medium-term solution here.

2022-08-05 20:53 UTC, merged